### ISSUE TITLE
Docker build时无法上网

### ISSUE THREAD

**Issue by wangtsiao** [huangzheng2016/CTFd-docker#1]
谢谢你开源的修改版本。

我在执行`docker-compose -f CTFd/docker-compose.yml up -d`命令时，发现无法连接中科大源。

把中科大源修改为清华源后依然连接失败，主机网络正常，已经排查网络问题。

**Comment by huangzheng2016** [comment]
你可以尝试修改根目录下的[sources.list](https://github.com/huangzheng2016/CTFd-docker/blob/master/sources.list)文件，这个是组建docker时所使用的源，如果可以提供失败的相关截图我可以排查一下问题

**Comment by wangtsiao** [comment]
感谢，问题已解决。
