### ISSUE TITLE
您好，我当前遇到了这个问题，由于暂时没有接触过这个框架，在网络上也没有找到相应的解决方案，能麻烦解答一下嘛？

### ISSUE THREAD

**Issue by opfelix** [huangzheng2016/CTFd-docker#4]
![image](https://github.com/huangzheng2016/CTFd-docker/assets/67058360/83830aa6-a45c-4599-a269-9992792b5394)

**Comment by huangzheng2016** [comment]
好像新版CTFd已经会自动配置网络，无需使用该步骤
