### ISSUE TITLE
請問如果不要使用網域名要直接使用IP要如何設定？

### ISSUE THREAD

**Issue by BensonRUEI** [huangzheng2016/CTFd-docker#6]
請問如果不要使用網域名要直接使用IP要如何設定？
可以讓題目產生出來的URL是 IP:PORT嗎？
謝謝您~

**Comment by huangzheng2016** [comment]
可以在docker-compose.yml中的direct_url直接填写ip（如果容器已经创建完可以直接修改whale后台配置中的directurl选项），并且在新建whale的ctfd题目时选择direct模式，这样就是IP:PORT形式了

**Comment by BensonRUEI** [comment]
有了~
非常感謝您
